services:

  user-postgres:
    image: postgres:16

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: msgr_users

    ports:
      - "5433:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d msgr_users"]
      interval: 5s
      timeout: 5s
      retries: 5

  post-postgres:
    image: postgres:16

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: msgr_posts

    ports:
      - "5434:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d msgr_posts"]
      interval: 5s
      timeout: 5s
      retries: 5

  user-migrate:
    image: migrate/migrate:latest

    depends_on:
      user-postgres:
        condition: service_healthy

    volumes:
      - ./services/user-service/migrations:/migrations

    command:
      [
        "-path", "/migrations",
        "-database", "postgres://postgres:postgres@user-postgres:5432/msgr_users?sslmode=disable",
        "up"
      ]

  post-migrate:
    image: migrate/migrate:latest

    depends_on:
      post-postgres:
        condition: service_healthy

    volumes:
      - ./services/post-service/migrations:/migrations

    command:
      [
        "-path", "/migrations",
        "-database", "postgres://postgres:postgres@post-postgres:5432/msgr_posts?sslmode=disable",
        "up"
      ]

  user-service:
    build:
      context: ./services/user-service

    depends_on:
      user-postgres:
        condition: service_healthy

      user-migrate:
        condition: service_completed_successfully

    environment:
      HTTP_PORT: 8080

      DB_HOST: user-postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: msgr_users
      DB_SSLMODE: disable

    ports:
      - "8080:8080"

  post-service:
    build:
      context: ./services/post-service

    depends_on:
      post-postgres:
        condition: service_healthy

      post-migrate:
        condition: service_completed_successfully

    environment:
      HTTP_PORT: 8080

      DB_HOST: post-postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: msgr_posts
      DB_SSLMODE: disable

    ports:
      - "8081:8080"